import type {
  AgeGroupFilter,
  LanguagesFilter,
  SpecialtyFilter,
  TestsFilter,
  VisitTypeFilter,
  WaitTimeFilter,
} from '@/types'

export const filterKeys = {
  ageGroup: 'ageGroup',
  waitTime: 'waitTime',
  visitType: 'visitType',
  specialty: 'specialty',
  tests: 'tests',
  languages: 'languages',
}

export const filterValues = {
  ageGroupOption0: 'adult' as AgeGroupFilter,
  ageGroupOption1: 'children' as AgeGroupFilter,
  waitOption0: 'sameDay' as WaitTimeFilter,
  waitOption1: 'weekWell' as WaitTimeFilter,
  waitOption2: 'weekSick' as WaitTimeFilter,
  waitOption3: 'twoMonths' as WaitTimeFilter,
  visitTypeOption0: 'primaryWell' as VisitTypeFilter,
  visitTypeOption1: 'primarySick' as VisitTypeFilter,
  visitTypeOption2: 'primarySports' as VisitTypeFilter,
  visitTypeOption3: 'primaryPrenatal' as VisitTypeFilter,
  visitTypeOption4: 'primaryWomen' as VisitTypeFilter,
  visitTypeOption5: 'primaryTelehealth' as VisitTypeFilter,
  visitTypeOption6: 'primaryVaccines' as VisitTypeFilter,
  specialtyOption0: 'mental' as SpecialtyFilter,
  specialtyOption1: 'dental' as SpecialtyFilter,
  specialtyOption2: 'eye' as SpecialtyFilter,
  specialtyOption3: 'podiatry' as SpecialtyFilter,
  specialtyOption4: 'mat' as SpecialtyFilter,
  specialtyOption5: 'nutrition' as SpecialtyFilter,
  specialtyOption6: 'tobacco' as SpecialtyFilter,
  specialtyOption7: 'pharmacy' as SpecialtyFilter,
  testsOption0: 'blood' as TestsFilter,
  testsOption1: 'sti' as TestsFilter,
  testsOption2: 'covid' as TestsFilter,
  testsOption3: 'mammo' as TestsFilter,
  testsOption4: 'xray' as TestsFilter,
  languageOption0: 'spanish' as LanguagesFilter,
  languageOption1: 'mandarin' as LanguagesFilter,
  languageOption2: 'vietnamese' as LanguagesFilter,
}
