name: Check Code
description: 'Check code compliance and testing'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 2

    - uses: pnpm/setup@v2

    - uses: actions/setup-node@v7
      with:
        node-version: 24
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Lint
      run: pnpm turbo lint

    - name: Format check
      run: pnpm turbo format:check

    - name: Type-check
      run: pnpm turbo type-check

    - name: Build
      run: pnpm turbo build
