name: Detect changed apps
description: 'Check which apps have changes that need to be shipped'
outputs:
  updated:
    description: 'Objects with app name and deploy role ARN'
    value: ${{ steps.detect-changes.outputs.updated }}

runs:
  using: 'composite'
  steps:
    - name: Check changed files
      id: detect-changes
      shell: bash
      run: |
        UPDATED_APPS=""
        DEPLOY_ARNS=""
        CHANGED=$(git diff --name-only HEAD^1 HEAD)
        echo "$CHANGED"

        packages_changed() { echo "$CHANGED" | grep -q "^packages/"; }
        app_changed() { echo "$CHANGED" | grep -q "^apps/$1/"; }
        ci_changed() { echo "$CHANGED" | grep -q "^\.github/"; }

        if packages_changed || app_changed "oem-flood-finder" || ci_changed; then
          UPDATED_APPS+=",{\"name\":\"oem-flood-finder\",\"role\":\"$secrets.AWS_DEPLOY_ROLE_ARN_311\"}"
        fi

        if packages_changed || app_changed "primary-care-finder" || ci_changed; then
          UPDATED_APPS+=",{\"name\":\"primary-care-finder\",\"role\":\"$secrets.AWS_DEPLOY_ROLE_ARN_311\"}"
        fi

        if packages_changed || app_changed "philly-311" || ci_changed; then
          UPDATED_APPS+=",{\"name\":\"philly-311\",\"role\":\"$secrets.AWS_DEPLOY_ROLE_ARN_311\"}"
        fi

        echo "updated=[${UPDATED_APPS:1}]" >> "$GITHUB_OUTPUT"
