// ABOUTME: Per-service-type color + Material-Symbols icon mapping ported from
// ABOUTME: native ServiceType.kt so map markers across web and native share a
// ABOUTME: visual language. Falls back to a neutral gray + "help" glyph for
// ABOUTME: unknown types, including any future service types added in Salesforce.

const COLORS: Record<string, string> = {
  'Abandoned Vehicle': '#734db3',
  'Abandoned Bike': '#4d8ce6',
  'Illegal Dumping': '#e63333',
  'Rubbish Collection': '#33b359',
  'Recyclables Collection': '#1aa68c',
  'Sanitation Violation': '#d9661a',
  'Dumpster Violation': '#bf4d1a',
  'Pothole Repair': '#99591a',
  'Cave-In Repair': '#b34026',
  Depression: '#8c6626',
  'Ditch Repair': '#735926',
  'Push-Up': '#a6731a',
  'Dangerous Sidewalk': '#d98c0d',
  'ADA Curb Ramp': '#1a80e6',
  'Line Striping': '#e6bf0d',
  'Street Light Outage': '#f2b30d',
  'Alley Light Outage': '#d98c0d',
  'Street Light (Other)': '#e6991a',
  'Street Light(Other)': '#e6991a',
  'Traffic Signal Emergency': '#f22626',
  'Stop Sign Repair': '#d91a33',
  'Property Maintenance Exterior': '#4d66cc',
  'Property Maintenance Interior': '#664dcc',
  'Exterior High Weeds': '#40b333',
  'Building Structurally Dangerous (Occupied)': '#e61a1a',
  'Building Structurally Dangerous (Vacant)': '#bf1a4d',
  'Vacant Lot': '#8c8c99',
  'Vacant Property': '#73738c',
  'Tree Maintenance': '#269933',
  'Street Trees': '#40bf4d',
  'Graffiti Removal': '#a61abf',
  'Dead Animal in Street': '#804d26',
  'Residential Fire Safety Complaint': '#f24010',
  'Smoke Detector': '#e6660d',
  'Inlet Cleaning': '#1a8ce6',
  'Hydrant Knocked Down': '#e61a26',
  'Manhole Cover Missing': '#4d4d59',
  'Manhole Other Problem': '#666673',
  'Homeless Encampment': '#8c59b3',
  'Parks and Rec Safety and Maintenance': '#1ab373',
  'Demolition Complaint': '#e6730d',
  'Work Underway without Permits': '#f2590d',
  'Work Underway in violation of permit requirements': '#d9400d',
  Salting: '#1a99d9',
  Shoveling: '#33b3f2',
  'Icy Road Surface': '#26bfe6',
  'Snow Removal': '#40a6f2',
  'Complaint (Streets)': '#737380',
  'Other (Streets)': '#666673',
  'Vendor Complaint': '#d9a60d',
  'Unlicensed Business Complaint': '#cc8c0d',
  'Short Term Rental Complaint': '#3373cc',
  'Plastic Bag Complaint': '#1aa6a6',
  'Needle Collection': '#bf1a66',
}

const ICONS: Record<string, string> = {
  'Abandoned Vehicle': 'directions_car',
  'Abandoned Bike': 'pedal_bike',
  'Illegal Dumping': 'delete',
  'Rubbish Collection': 'delete_outline',
  'Recyclables Collection': 'recycling',
  'Sanitation Violation': 'warning',
  'Dumpster Violation': 'no_backpack',
  'Pothole Repair': 'construction',
  'Cave-In Repair': 'arrow_downward',
  Depression: 'arrow_circle_down',
  'Ditch Repair': 'minimize',
  'Push-Up': 'arrow_circle_up',
  'Dangerous Sidewalk': 'directions_walk',
  'ADA Curb Ramp': 'accessible',
  'Line Striping': 'traffic',
  'Street Light Outage': 'lightbulb_off',
  'Alley Light Outage': 'nightlight_off',
  'Street Light (Other)': 'lightbulb',
  'Street Light(Other)': 'lightbulb',
  'Traffic Signal Emergency': 'traffic_jam',
  'Stop Sign Repair': 'stop_circle',
  'Property Maintenance Exterior': 'apartment',
  'Property Maintenance Interior': 'maps_home_work',
  'Exterior High Weeds': 'grass',
  'Building Structurally Dangerous (Occupied)': 'domain_verification',
  'Building Structurally Dangerous (Vacant)': 'domain_disabled',
  'Vacant Lot': 'crop_16_9',
  'Vacant Property': 'home',
  'Tree Maintenance': 'park',
  'Street Trees': 'nature',
  'Graffiti Removal': 'brush',
  'Dead Animal in Street': 'pets',
  'Residential Fire Safety Complaint': 'local_fire_department',
  'Smoke Detector': 'sensors',
  'Inlet Cleaning': 'water',
  'Hydrant Knocked Down': 'opacity',
  'Manhole Cover Missing': 'radio_button_unchecked',
  'Manhole Other Problem': 'do_not_disturb',
  'Homeless Encampment': 'cabin',
  'Parks and Rec Safety and Maintenance': 'sports_handball',
  'Demolition Complaint': 'handyman',
  'Work Underway without Permits': 'warning_amber',
  'Work Underway in violation of permit requirements': 'cancel',
  Salting: 'ac_unit',
  Shoveling: 'snowing',
  'Icy Road Surface': 'device_thermostat',
  'Snow Removal': 'snowshoeing',
  'Complaint (Streets)': 'chat',
  'Other (Streets)': 'more_horiz',
  'Vendor Complaint': 'shopping_cart',
  'Unlicensed Business Complaint': 'business_center',
  'Short Term Rental Complaint': 'other_houses',
  'Plastic Bag Complaint': 'shopping_bag',
  'Needle Collection': 'vaccines',
}

const FALLBACK_COLOR = '#666673'
const FALLBACK_ICON = 'help'

export function serviceTypeColor(serviceType: string | undefined | null): string {
  if (!serviceType) return FALLBACK_COLOR
  return COLORS[serviceType] ?? FALLBACK_COLOR
}

export function serviceTypeIcon(serviceType: string | undefined | null): string {
  if (!serviceType) return FALLBACK_ICON
  return ICONS[serviceType] ?? FALLBACK_ICON
}
