name: CI

on:
  pull_request:
  push:
    branches: [main, test]

jobs:
  check:
    name: Lint, type-check, build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2
      - name: (Action) Check code
        uses: ./.github/actions/check-code

  detect-changes:
    name: Detect changed apps
    runs-on: ubuntu-latest
    needs: check
    outputs:
      updated: ${{ steps.changes.outputs.updated }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: (Action) detect changes
        id: changes
        uses: ./.github/actions/detect-changes
        with:
          branch: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/test' && 'test') || 'dev' }}

  ship-apps:
    name: Ship updated Pinboard apps
    runs-on: ubuntu-latest
    needs: detect-changes
    env:
      branch: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/test' && 'test') || 'dev' }}
    strategy:
      matrix:
        app: ${{ fromJSON(needs.detect-changes.outputs.updated) }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: (Action) Ship to ${{ env.branch }} with ctl
        # if: github.event.push
        uses: ./.github/actions/ship-app
        with:
          app-name: ${{ matrix.app.name }}
          environment-name: ${{ env.branch }}
          role-arn: ${{ secrets.${matrix.app.role} }}
        env:
          VITE_311_SSO_CLIENT_ID: ${{ matrix.app.name == 'philly-311' && secrets.SSO_311_CLIENT_ID }}
          VITE_311_SSO_TENANT: ${{ matrix.app.name == 'philly-311' && ((env.branch == 'prod' && secrets.SSO_311_TENANT_PROD) || (env.branch == 'test' && secrets.SSO_311_TENANT_TEST) || secrets.SSO_311_TENANT_DEV) }}
          VITE_311_SSO_AUTHORITY_DOMAIN: ${{ matrix.app.name == 'philly-311' && ((env.branch == 'prod' && secrets.SSO_311_AUTHORITY_DOMAIN_PROD) || (env.branch == 'test' && secrets.SSO_311_AUTHORITY_DOMAIN_TEST) || secrets.SSO_311_AUTHORITY_DOMAIN_DEV) }}
          VITE_311_SSO_REDIRECT_URI: ${{ matrix.app.name == 'philly-311' && ((env.branch == 'prod' && secrets.SSO_311_REDIRECT_URI_PROD) || (env.branch == 'test' && secrets.SSO_311_REDIRECT_URI_TEST) || secrets.SSO_311_REDIRECT_URI_DEV) }}
          VITE_311_SSO_API_SCOPE: ${{ matrix.app.name == 'philly-311' && ((env.branch == 'prod' && secrets.SSO_311_API_SCOPE_PROD) || (env.branch == 'test' && secrets.SSO_311_API_SCOPE_TEST) || secrets.SSO_API_SCOPE_DEV) }}
          VITE_311_API_URL: ${{ matrix.app.name == 'philly-311' && ((env.branch == 'prod' && secrets.API_311_URL_PROD) || (env.branch == 'test' && secrets.API_311_URL_TEST) || secrets.API_311_URL_DEV) }}
          VITE_311_API_BASE_URL: ${{ matrix.app.name == 'philly-311' && '/api' }}
          VITE_311_API_PROXY: ${{ matrix.app.name == 'philly-311' && ((env.branch == 'prod' && '/prod') || (env.branch == 'test' && '/test') || '/dev') }}
          VITE_311_AIS_BASE_URL: ${{ matrix.app.name == 'philly-311' && secrets.AIS_URL }}
