name: CI

on:
  pull_request:
  push:
    branches: [main, test, task/make-usable-on-test-site]

jobs:
  # check:
  #   name: Lint, type-check, build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v7
  #       with:
  #         fetch-depth: 2
  #     - name: (Action) Check code
  #       uses: ./.github/actions/check-code

  detect-changes:
    name: Detect changed apps
    runs-on: ubuntu-latest
    # needs: check
    outputs:
      updated: ${{ steps.changes.outputs.updated }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: (Action) detect changes
        id: changes
        uses: ./.github/actions/detect-changes
        with:
          branch: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/test' && 'test') || 'dev' }}

  # ship-apps:
  #   name: Ship updated Pinboard apps
  #   runs-on: ubuntu-latest
  #   needs: detect-changes
  #   env:
  #     branch: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/test' && 'test') || 'dev' }}
  #   strategy:
  #     matrix:
  #       app: ${{ fromJSON(needs.detect-changes.outputs.updated) }}
  #   permissions:
  #     id-token: write
  #     contents: read

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v7
  #       with:
  #         fetch-depth: 2

  #     - name: Ship to ${{ env.branch }} with ctl
  #       uses: ./.github/actions/ship-app
  #       with:
  #         app-name: ${{ matrix.app.name }}
  #         environment-name: ${{ env.branch }}
  #         role-arn: ${{ matrix.app.role }}
